## 使用 xLearn 实现 FM

### 数据格式

In [5]:
import pandas as pd

df = pd.read_csv('../data/criteo-kaggle/train.tiny.csv', delimiter='\t', header=None)
df

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,0,1.0,1,5.0,0.0,1382,4.0,15,2,181,...,e5ba7672,f54016b9,21ddcdc9,b1252a9d,07b5194c,NaN,3a171ecb,c5c50484,e8b83407,9727dd16
1,0,2.0,0,44.0,1.0,102,8.0,2,2,4,...,07c540c4,b04e4670,21ddcdc9,5840adea,60f6221e,NaN,3a171ecb,43f13e8b,e8b83407,731c3655
2,0,2.0,0,1.0,14.0,767,89.0,4,2,245,...,8efede7f,3412118d,NaN,NaN,e587c466,ad3062eb,3a171ecb,3b183c5c,NaN,NaN
3,0,NaN,893,NaN,NaN,4392,NaN,0,0,0,...,1e88c74f,74ef3502,NaN,NaN,6b3a5ca6,NaN,3a171ecb,9117a34a,NaN,NaN
4,0,3.0,-1,NaN,0.0,2,0.0,3,0,0,...,1e88c74f,26b3c7a7,NaN,NaN,21c9516a,NaN,32c7478e,b34f3128,NaN,NaN
5,0,NaN,-1,NaN,NaN,12824,NaN,0,0,6,...,776ce399,92555263,NaN,NaN,242bb710,8ec974f4,be7c41b4,72c78f11,NaN,NaN
6,0,NaN,1,2.0,NaN,3168,NaN,0,1,2,...,776ce399,cdfa8259,NaN,NaN,20062612,NaN,93bad2c0,1b256e61,NaN,NaN
7,1,1.0,4,2.0,0.0,0,0.0,1,0,0,...,e5ba7672,74ef3502,NaN,NaN,5316a17f,NaN,32c7478e,9117a34a,NaN,NaN
8,0,NaN,44,4.0,8.0,19010,249.0,28,31,141,...,e5ba7672,42a2edb9,NaN,NaN,0014c32a,NaN,32c7478e,3b183c5c,NaN,NaN
9,0,NaN,35,NaN,1.0,33737,21.0,1,2,3,...,d4bb7bd8,70d0f5f9,NaN,NaN,0e63fca0,NaN,32c7478e,0e8fe315,NaN,NaN

从上面可以看出 criteo 提供的 39 个数据维度，每个维度都有不同程度的缺失值。使用 FM, FFM 我需要将每个维度 field 中的出现的惟一值都转换成特征 value。即 one-hot 编码。

### one hot encoding